### ISSUE TITLE
Could this support video models? 

### ISSUE THREAD

**Issue by john2stai** [Extraltodeus/Skimmed_CFG#10]
Since dynamic cfg could help reduce generation time, just wondering could this also work on video models such as LTXV or hunyuan?

**Comment by Extraltodeus** [comment]
I absolutely have not tested with recent video models. Only animatediff. It should however with anything using a negative prediction/CFG scale.

**Comment by john2stai** [comment]
> I absolutely have not tested with recent video models. Only animatediff. It should however with anything using a negative prediction/CFG scale.

Thanks for your reply! I tried automatic cfg with LTX, but it didn't work. I will try skimmed cfg later. 
Happy holidays!

**Comment by Extraltodeus** [comment]
Thank you, you too! :)
