### ISSUE TITLE
'ModelPatcher' object has no attribute 'set_model_sampler_pre_cfg_function'

### ISSUE THREAD

**Issue by leifniem** [Extraltodeus/Skimmed_CFG#4]
Trying to run the example everything workflow i encounter the following error.

```
Error occurred when executing Skimmed CFG:

'ModelPatcher' object has no attribute 'set_model_sampler_pre_cfg_function'

  File "E:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\Skimmed_CFG\skimmed_CFG.py", line 50, in patch
    m.set_model_sampler_pre_cfg_function(pre_cfg_patch)
```

**Comment by Extraltodeus** [comment]
Hello!

This is due to other nodes like automatic-cfg

Don't run any of these (restart the UI if you did) and it should work

otherwise it comes from another node and I can not help.

**Comment by leifniem** [comment]
Hi again :)

Just wanted to report that even removing AutomaticCFG completely sadly did not fix it, if i find a fix in the future i'll let you know. Thanks for the cool Node!

**Comment by Extraltodeus** [comment]
Try to see if in the error messasge there is the name of another node because this just means that the pipeline does not exist. And if so, either you have an outdated version of ComfyUI or there is some other node which replaces the function that contains it within comfyui

**Comment by leifniem** [comment]
I cleaned up my unused nodes and updated everything and it seems to be working now. Sorry for the unnecessary report 🙈

**Comment by Extraltodeus** [comment]
No problem!
