### ISSUE TITLE
Skimmed_CFG for Lightning models

### ISSUE THREAD

**Issue by juancopi81** [Extraltodeus/Skimmed_CFG#8]
Hi there, 
Thank you very much for this great extension! I've been playing around with it and was wondering about two things:

- Would you have any recommendations for working with SDXL Lighting models that use a low CFG, of say 2?
- In the code you have:

```
            conds_out[1] = skimmed_CFG(x_orig, conds_out[1], conds_out[0], cond_scale, practical_scale if not full_skim_negative else 0, flip_filter)
            conds_out[0] = skimmed_CFG(x_orig, conds_out[0], conds_out[1], cond_scale, practical_scale, flip_filter)
```

Is conds_out[1] the conditional or unconditonal pred.? I am confused after seeing [this implementation](https://github.com/Panchovix/stable-diffusion-webui-reForge/blob/dev_upstream/extensions-builtin/reForge-SkimmedCFG/skimmed_CFG/skimmed_CFG.py#L75).

Thanks again!

**Comment by Extraltodeus** [comment]
Hello!

So 0 is the positive and 1 is the negative. The thing is that I do the same operation a second time after swapping them. This removes overblown values that are now out of check from the positive prediction.

As for lightning models I do not use them so I sincerely have no idea. I'd recommand to try and see simply.

**Comment by juancopi81** [comment]
Thank you very much for your answer!
